services:
  orthanc:
    image: orthancteam/orthanc
    container_name: orthanc
    ports:
      - "4242:4242"
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json

  nginx:
    image: nginx:alpine
    container_name: orthanc-nginx
    ports:
      - "8042:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orthanc